# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
plugins:
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.3

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/PredicateMatcher:
  Strict: false
  EnforcedStyle: inflected

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/SignalException:
  EnforcedStyle: semantic
